### PR TITLE
include vector fixes compile error in stoke

### PR DESCRIPTION
**Pull request by UplinkCoder**

### CODE REVIEW

**Comment by stefanheule** [comment]
Thanks for the pull request.  Could you briefly explain why this change is necessary, please?  I don't see any use of vector in this file.

**Comment by UplinkCoder** [comment]
Sure it is used in line 329 - line 333

**Comment by stefanheule** [comment]
My bad.  I will merge your request.

**Comment by UplinkCoder** [comment]
Thanks!

**Pull request merged**
